<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/Pandasdailypractice4_Ex3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
#Step 3. Assign it to a variable called users and use the 'user_id' as index

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'

users = pd.read_csv(url, sep='|')

users = users.set_index('user_id')

In [5]:
#Step 4. See the first 25 entries

users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [6]:
#Step 5. See the last 10 entries

users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [10]:
#Step 6. What is the number of observations in the dataset?

len(users)

943

In [18]:
#Step 7. What is the number of columns in the dataset?

len(users.columns)

4

In [16]:
users.shape

(943, 4)

In [19]:
#Step 8. Print the name of all the columns.

users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [20]:
#Step 9. How is the dataset indexed?

users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [22]:
#Step 10. What is the data type of each column?

users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [23]:
#Step 11. Print only the occupation column

users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [24]:
#Step 12. How many different occupations are in this dataset?

number_of_occupations = users['occupation'].nunique()

number_of_occupations

21

In [25]:
#Step 13. What is the most frequent occupation?

most_frequest_occupation = users['occupation'].mode()

most_frequest_occupation

0    student
Name: occupation, dtype: object

In [27]:
#Step 14. Summarize the DataFrame.

users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [28]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

In [29]:
#Step 14. Summarize the DataFrame.

users.describe(include = 'all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [32]:
#Step 16. Summarize only the occupation column

users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [33]:
#Step 17. What is the mean age of users?

mean_age_of_users = users['age'].mean()

mean_age_of_users

34.05196182396607

In [34]:
#Step 18. What is the age with least occurrence?

age_with_least_occurence = users['age'].value_counts().idxmin()

age_with_least_occurence

7