<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/Pandasdailypractice3_MPGcars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd

import numpy as np

In [17]:
#Step 2. Import the first dataset cars1 and cars2.
#Step 3. Assign each to a variable called cars1 and cars2

cars1 = pd.read_csv("cars1.csv")
cars2 = pd.read_csv("cars2.csv")

In [14]:
#Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

cars1 = cars1.loc[:, ~cars1.columns.str.contains('^Unnamed')]

In [19]:
#Step 5. What is the number of observations in each dataset?

num_obs_cars1 = len(cars1)
num_obs_cars2 = len(cars2)

print("Number of observations in cars1:", num_obs_cars1)
print("Number of observations in cars2:", num_obs_cars2)

Number of observations in cars1: 198
Number of observations in cars2: 200

In [22]:
#Step 6. Join cars1 and cars2 into a single DataFrame called cars

cars = pd.concat([cars1, cars2])

cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

random_owners = pd.Series(np.random.randint(15000, 73001, size=len(cars)))

In [31]:
#Step 8. Add the column owners to cars

cars['owners'] = random_owners

cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,22937
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,41668
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,53411
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,45012
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,27005

In [32]:
cars.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'owners'],
      dtype='object')